# Generated by Django 3.0.7 on 2020-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_auto_20200712_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='average',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
