# Generated by Django 3.0.7 on 2020-07-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwards.Profile'),
        ),
    ]
